version: "3.9"

services:
  server:
    container_name: flygoose-api
    image: ${IMAGE_NAME}:${VERSION}
    env_file:
      - ./.env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "29090:29090"
    volumes:
      - ../conf:/apps/flygoose/conf
      - ../config.yaml:/apps/flygoose/config.yaml
      - ../flygoose.db:/apps/flygoose/flygoose.db
      - ../static:/apps/flygoose/static
    restart: on-failure
    networks:
      - flygoose

networks:
  flygoose:
    driver: bridge