version: "3.9"

services:
  nginx:
     # 容器名
     container_name: nginx
     # 使用的镜像
     image: nginx
     # 卷挂载
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/html:/usr/share/nginx/html:ro
       - ./nginx/conf.d:/etc/nginx/conf.d
       - ./nginx/logs:/var/log/nginx
     # 与宿主机的端口映射
     ports:
       - "80:80"
     # 指定容器退出后的重启策略为始终重启
     # restart: on-failure
     networks:
      - flygoose

networks:
  flygoose:
    driver: bridge